api:
  listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
  username: "admin"  # default "", Basic auth for WebUI
  password: "pass"   # default "", Basic auth for WebUI
  base_path: "/rtc"  # default "", API prefix for serving on suburl (/api => /rtc/api)
  static_dir: "www"  # default "", folder for static files (custom web interface)
  origin: "*"        # default "", allow CORS requests (only * supported)
  tls_listen: ":443" # default "", enable HTTPS server
rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  username: "admin"  # optional, default - disabled
  password: "pass"   # optional, default - disabled
  default_query: "video&audio"  # optional, default codecs filters
streams:
  camera_001: rtsp://somba-maluku-minipcbb:8554/camera-001
  camera_002: rtsp://somba-maluku-minipcbb:8554/camera-001
  camera_003: rtsp://somba-maluku-minipcbb:8554/camera-001
  camera_001a: rtsp://admin:Bogor2025%23@103.155.46.226:554/Streaming/Channels/502/
  camera_002a: rtsp://admin:Bogor2025%23@103.155.46.226:554/Streaming/Channels/702/
  camera_003a: rtsp://admin:Bogor2025%23@103.155.46.226:554/Streaming/Channels/102/
